from dotenv import load_dotenv
import os

load_dotenv()
REGION = os.getenv("REGION")
BUCKET_NAME = os.getenv("BUCKET_NAME")
PROFILE_MAIN = os.getenv("MAIN_PROFILE")
PROFILE_SECONDARY = os.getenv("SECONDARY_PROFILE")
REDSHIFT_CLUSTER_IDENTIFIER = os.getenv("REDSHIFT_CLUSTER_IDENTIFIER")
REDSHIFT_ROLE_ARN = os.getenv("REDSHIFT_ROLE_ARN")
REDSHIFT_DBNAME = os.getenv("REDSHIFT_DBNAME")
REDSHIFT_MASTER_USERNAME = os.getenv("REDSHIFT_MASTER_USERNAME")
REDSHIFT_MASTER_PASSWORD = os.getenv("REDSHIFT_MASTER_PASSWORD")
